### ISSUE TITLE
Ansible 2.0 problem

### ISSUE THREAD

**Issue by usterk** [vrischmann/ansible-role-java#7] opened 2015-12-28 23:27 UTC
I have a problem while running this role with ansible 2.0 running on ubuntu 14.04 (it is working on older Ansible version): 

`java_versions` is set to `oracle-java8-installer`

Error: 
`fatal: [app-backend1]: FAILED! => {"failed": true, "msg": "ERROR! The conditional check 'item|search(\"^oracle\")' failed. The error was: ERROR! an unexpected type error occurred. Error was expected string or buffer\n\nThe error appears to have been in '/var/lib/jenkins/jobs/run-test/workspace/roles/java/tasks/oracle.yml': line 9, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Install Oracle Java\n  ^ here\n"}`

I have fixed it with commenting out `when` statement. I don't need it there: 

```
- name: Install Oracle Java
  tags: java
  apt: name={{ item }} update-cache=yes state=latest
#  when: item|search("^oracle")
  with_items: java_versions
```

**Comment by vrischmann** [comment] 2015-12-29 09:58
Hi, thanks for the report.

I'm not using Ansible 2.0 right now, but when I get to it I'll take a look.

**Comment by badrange** [comment] 2016-06-01 12:59
This issue bit me too.

**Comment by vrischmann** [comment] 2016-06-01 13:13
Hi, sorry totally forgot about this issue. I can't test right now, but I did some cleanup last month, and I think I used Ansible 2.0 at that time. Could you test again with the last version ?

**Comment by badrange** [comment] 2016-06-01 13:59
Thanks for the super-duper-quick answer! I actually did, and it still didn't work for me. Also, it didn't choose the correct java version with the most recent version (as far as I could tell).

**Comment by vrischmann** [comment] 2016-06-01 14:40
Ok, thanks. I'll try to debug that tonight.

**Comment by vrischmann** [comment] 2016-06-02 08:32
So I tested again on my server with Ansible 2.0.2.0, with this defined in `host_vars/myserver`

    java_versions:
      - oracle-java8-installer

And a simple playbook:

    ---
    - hosts: "vrischmann.me"

      roles:
        - { role: java }

run that playbook and it installed `oracle-java8-installer` correctly.
I even tested this on a freshly installed Debian Jessie in a VM, just to be sure, same results.

Could you try this on your end ? If it still doesn't work please give me a reproducible test case.

**Comment by vrischmann** [comment] 2016-06-02 08:34
Forgot to mention, I just added ansible-role-java using git submodule into `roles/java`.

**Comment by evnm** [comment] 2016-09-12 23:10
This issue is affecting my company's VM build pipeline.

I'm running Ansible 2.1.1.0 and `ansible-galaxy` is pulling in `vrischmann.java` master. My playbook matches the configuration supplied by @vrischmann above almost to the letter:

```
---
...
  roles:
    ...
    - role: vrischmann.java
      java_versions: oracle-java8-installer
```

**Comment by vrischmann** [comment] 2016-09-13 08:21
I don't use ansible galaxy.

1) Is it pulling the HEAD of this repository ? If it is, then you can't have the same error as above because the file `oracle.yml` doesn't even exist anymore, there's only `main.yml` now.
If it isn't pulling the HEAD, you need to find a way to make it do so because I don't support previous commits.

2) If it IS pulling the HEAD and you do have an error in that configuration, please open a new issue with the complete error.

**Comment by evnm** [comment] 2016-09-13 22:00
Thanks for the reply. I think you're intuition is correct—I suspect Ansible Galaxy is pulling in a previous commit of master.

Would you be opposed to putting out versioned releases of `ansible-role-java` in future? While I chock up my confusion to ansible-galaxy's lack of role-updatability, it would be clearer what version of the role is being relied upon if a specific version was listed instead of `master`.

**Comment by vrischmann** [comment] 2016-09-14 10:28
I'm looking at https://galaxy.ansible.com/vrischmann/java/ and I have no idea why the supported platforms are not up to date, or why it's not pulling HEAD. When I included the meta file for galaxy support two years ago I don't think I did anything else than simply pushing the file, so I'm confused as to why it's not being updated automatically. 

I'll have to document myself better on how exactly I'm supposed to keep stuff up to date on galaxy. I'll probably add a tag 1.0 at that time.

**Comment by evnm** [comment] 2016-09-14 17:12
The Ansible Galaxy service itself pulls in HEAD properly. I meant that client machines cannot upgrade installed roles (i.e. in a way akin to `pip install -U`) without explicitly removing and reinstalling the role. This is unavoidable, given the way Galaxy is designed, but tagging [semantically-versioned](http://semver.org/) releases of the role would let users more easily track what version they're relying upon. As an example, see the list of versioned releases on [this role](https://galaxy.ansible.com/whiskerlabs/python/) that I maintain.

Anyway, I'm not meaning to criticize anything here. We've been using ansible-role-java for over a year now at my company and have been happy with it. :)

**Comment by vrischmann** [comment] 2016-09-14 17:39
No worries, I was just trying to understand how galaxy works. If I understand correctly I simply need to add a git tag. I'll do that after updating the meta file. 

If you managed to resolve your problem, I think I'll close this issue.

**Closed as completed** 2016-09-17 09:09 UTC
